##############################
#           CONFIG           #
##############################

token: ""
license_key: ""
prefix: '-'

status:
  [
    { type: "Watching", name: "{members} members", status: "online" },
    { type: "Watching", name: "{tickets} tickets", status: "online" },
    { type: "Watching", name: "{bots} bots", status: "online" },
  ]

EmbedColors:
  Default: "#d53370"
  Error: "#f52c2c"
  Success: "#25de1f"

##############################
#      Erno Bot Modules      #
##############################

Modules: # is Enabled?
  management: true,
  admin: true,
  exp: true,
  moderation: true,
  utils: true,
  addon: true,
  info: true,
  fun: true,
  economy: true,
  dev: true,
  owner: true,
  ticket: true

##############################
#      Commands  Config      #
##############################

Help:
  Type: "categories"

Tickets:
  Name: "ticket-{user-username}"
  Category: "â”€â”€â”€â”€â”€ï¹’HALLWAYï¹’â”€â”€â”€â”€â”€"
  Staff: 
    - 'Admin'
  MentionUser: true
  MentionStaff: true
  Buttons: 
    Close: 
      label: "Close"
      emoji: "ğŸ—‘ï¸"
      style: 1

##############################
#      Channels & Logs       #
##############################

# Remove value to disable certain log
# Run command -reload all

#        Join & Leave          #
Welcome: "ï¼šê’°ğŸ‘‹ê’±ï¹’welcome"
Leave: "ï¼šê’°ğŸ™Œê’±ï¹’goodbye"
InviteChannel: "ï¼šê’°ğŸ‘‹ê’±ï¹’welcome"

JoinRoles:
  enabled: true
  roles:
    - Member

Verification:
  enabled: true
  disabled_dm_notification: "ï¼šê’°âœ…ê’±ï¹’verify"
  verification_logs: 'ï¼šê’°ğŸ“©ê’±ï¹’invites'
  verified_role: "Verified"


#         Moderation           #
MessageDelete: "ï¼šê’°ğŸ‘‹ê’±ï¹’modlogs"
MessageUpdate: "ï¼šê’°ğŸ‘‹ê’±ï¹’modlogs"


#        Administrator         #
ChannelCrete: ""
ChannelDelete: ""
ChannelUpdate: ""

##############################
#      Antilink System       #
##############################

Antilink:
  enabled: true
  whitelist_channels: []
  whitelist_users: []
  whitelist_roles: []
  whitelisted_domains: 
    - "google.com"

