Permission:
  title: "`âŒ` | No Perms"
  description: "> You don't have permission to run this command."
  color: "error"
  timestamp: true

Usage:
  title: "`âŒ` | Invalid Usage"
  description: "**Invalid Command Usage:**\n> `{usage}`"
  color: "error"
  timestamp: true

MissingMember:
  title: "`âŒ` | Missing Member"
  description: "> I couldn't find that member in the guild!"
  color: "error"
  timestamp: true

Cooldown:
  title: "`âŒ` | Cooldown"
  description: "{user-mention}, Please wait {remaining-time} seconds before using `{command}`"
  color: "default"
  timestamp: true

No_Reason: "No reason provided!"

# Utils ....

Help:
  title: "`â“` | Help"
  color: "default"
  timestamp: true
  footer: "{guild-name}"
  footerIcon: "{guild-icon}"

Ping:
  title: "`â³` | Ping"
  color: "default"
  timestamp: true

Userinfo:
  title: "`ğŸ‘¤` | User Info"
  fields:
    - name: "â¯ Username"
      value: "{user_username}"
      inline: true
    - name: "â¯ ID"
      value: "{user_id}"
      inline: false
    - name: "â¯ Bot"
      value: "{bot}"
      inline: false
    - name: "â¯ Joined Discord"
      value: "{created_at}"
      inline: false
    - name: "â¯ Level"
      value: "{level}"
      inline: true
    - name: "â¯ Exp"
      value: "{exp}"
      inline: true
    - name: "â¯ Progress"
      value: "{progressExp}"
      inline: true
  thumbnail: "{user_avatar}"
  color: "success"
  timestamp: true

Serverinfo:
  title: "`ğŸŒ` | Server Info"
  fields:
    - name: "â¯ Server Name"
      value: "{guild-name}"
      inline: true
    - name: "â¯ ID"
      value: "{guild-id}"
      inline: true
    - name: "â¯ Members"
      value: "{guild-membercount}"
      inline: false
    - name: "â¯ Channels"
      value: "{guild-channelcount}"
      inline: true
    - name: "â¯ Roles"
      value: "{guild-rolecount}"
      inline: true
    - name: "â¯ Owner"
      value: "{guild-owner} `({guild-ownerid})`"
      inline: false
  thumbnail: "{guild-icon}"
  color: "default"
  timestamp: true

# Admin

FetchInvites:
  title: "`ğŸ”’` | Fetch Server Invites"
  description: "Server invites have been fetched successfully!"
  footer: "Total invites fetched: {size}"
  footerIcon: "{guild-icon}"
  color: "default"
  timestamp: true

Say:
  Embed:
    title: "`ğŸ“¢` | {guild-name}"
    description: "> {content}"
    color: "default"
    timestamp: true
  Sent:
    title: "{user-username}"
    description: "> Your message has been sent!"
    color: "default"
    timestamp: true

XpAdd:
  title: "Xp Add"
  description: "> {user-mention} has gained {xp} XP and reached new level: {level}"
  color: "default"
  timestamp: true

XpRemove:
  title: "Xp Remove"
  description: "> {user-mention} has lost {xp} XP and now is on level: {level}"
  color: "default"
  timestamp: true

Embed: 
  title: "Embed sent successfully!"
  description: "> Your embed `{embed-name}` has been sent in {channel-mention}"
  color: "default"
  timestamp: true

# Moderation

Clear:
  Success:
    title: "`âœ…` | Messages Cleared"
    description: "> {amount} messages cleared by {user-mention} in {channel-mention}"
    color: "success"
    timestamp: true
  Unable_to_clear:
    title: "`âŒ` | Unable to Clear"
    description: "> I couldn't delete the specified number of messages, messages older than 14 days cannot be deleted!"
    color: "error"

Ban:
  Success:
    title: "`ğŸ’¢` | Banned"
    description: "> {user-mention} has been successfully banned by {staff-mention}"
    color: "success"
    timestamp: true
  Higher_Staff:
    title: "Ban Error"
    description: "> You are not allowed to ban users with a role higher than yours."
    color: "error"
    timestamp: true
  Staff_Member:
    title: "Ban Error"
    description: "> You are not allowed to ban staff members."
    color: "error"
    timestamp: true

Kick:
  Success:
    title: "`ğŸ’¢` | Kicked"
    description: "> {user-mention} has been successfully kicked by {staff-mention}"
    color: "success"
    timestamp: true
  Higher_Staff:
    title: "Kick Error"
    description: "> You are not allowed to kick users with a role higher than yours."
    color: "error"
    timestamp: true
  Staff_Member:
    title: "Kick Error"
    description: "> You are not allowed to kick staff members."
    color: "error"
    timestamp: true

History:
  NoHistory: "{user-username} doesn't have punishment history!"
  History:
    title: "Punishment History"
    description: "{user-mention}'s Punishments:\n{history}"
    color: "default"
    timestamp: true
    footer: "{guild-name}"
    footerIcon: "{guild-icon}"

Forceban:
  AlredyBanned:
    title: "`ğŸ’¢` | Forceban"
    description: "> {user-mention} is already banned in {guild-name}"
    color: "error"
    timestamp: true
  Success:
    title: "`ğŸ’¢` | Forceban"
    description: "> {user-mention} has been successfully force-banned by {staff-mention}"
    color: "success"
    timestamp: true

# Management

Prefix:
  title: "`ğŸŒ` | Prefix Set"
  description: "> The prefix for this server has been set to `{prefix}`."
  color: "default"
  footer: "{guild-name}"
  footerIcon: "{guild-icon}"
  timestamp: true

Setup:
  title: "Bot Setup"
  description: "> Bot setup has been completed successfully!"
  color: "default"
  timestamp: true
  footer: "{bot-username}"
  footerIcon: "{bot-pfp}"

# EXP

Leveltop:
  format: "**{position}: **{user-mention} â¯ `{level}` level â¯ `{exp}` exp"
  Embed:
    title: "â¯ Exp Top"
    description: "{formatedData}"
    color: "default"
    timestamp: true
    footer: "{guild-name}"
    footerIcon: "{guild-icon}"

Level:
  NoLevel:
    title: "{user-username} doesn't have any levels."
    color: "error"
  LevelMessage: "Level: {level}\nExp: {exp}\nYou need {neededExp} more exp to levelup!"

# Other

Boosters:
  Embed:
    title: "`ğŸ©·` | Boosters"
    description: "{boosters}"
    color: "default"
    timestamp: true
    footer: "{guild-name}"
  No_Boosters: "There is no active boosters in this server!"

Uptime:
  title: "Bot Uptime"
  description: "The bot has been online for **{uptime}**"
  timestamp: true
  color: "default"
  footer: "Erno"
  footerIcon: "{bot-pfp}"

# Tickets

New:
  Open:
    title: "New Ticket"
    description: "> {user-mention} has opened a new ticket: [{ticket-name}]({link})"
    color: "default"
    timestamp: true
  Missing:
    title: "Ticket Error"
    description: "> There is missing: {type} : {missing}, please create it!"
    color: "error"
    timestamp: true
  TicketMessageEmmbed:
    title: "`ğŸ«` | Ticket Open"
    description: "Hello, {user-mention}!\n\n> Please describe your problem, staff will be here asap!"
    color: "default"
    timestamp: true

Close:
  Closed:
    title: "Ticket Closed"
    description: "> {user-mention} has closed the ticket: [{ticket-name}]({link})"
    color: "success"
    timestamp: true
  Not_A_Ticket:
    title: "Not a ticket"
    description: "> This channel is not a ticket channel, or the ticket is unavailable in the database."
    color: "error"
    timestamp: true

TicketStats:
  Stats:
    title: "Ticket Stats"
    description: "There is your ticket stats!"
    fields:
      - name: "Total Tickets"
        value: "{total-tickets}"
        inline: true
      - name: "Open Tickets"
        value: "{open-tickets}"
        inline: true
      - name: "Closed Tickets"
        value: "{closed-tickets}"
        inline: true
      - name: "Average Solving Time"
        value: "{solving-time}"
        inline: true
      - name: "Most Tickets User"
        value: "{most-tickets-per-user}"
        inline: true
    color: 'default'
    timestamp: true
    footer: "{guild-name}"
    footerIcon: "{guild-icon}"
  No_Tickets:
    title: "No Tickets"
    description: "> There are no tickets in this server!"
    color: "error"
    timestamp: true

# Leveling and Other

Levelup:
  title: "Level Up!"
  description: "> {user-mention} has reached level {level}!"
  color: "default"
  footer: "{guild-name}"
  footerIcon: "{guild-icon}"
  timestamp: true

Id:
  title: "`ğŸ”` | Id Lookup"
  color: "default"
  timestamp: true,
  footer: "{guild-name}"
  footerIcon: "{guild-icon}"

Avatar:
  title: "`ğŸ–¼ï¸` | Avatar"
  description: "> [Click here to view avatar]({user-pfp})"
  color: "default"
  image: "{user-pfp}"
  timestamp: true

Welcome: "Welcome to our server {user-username}, you are the #{memberCount} member!"
Leave: "Goodbye {user-username}, we hope to see you again soon!\nTotal members: {memberCount}"
InviteMessage: "> ğŸ‰ {user-mention} was invited by {inviter-username} used invite: {invite-url}"
Disabled_dm: "âš ï¸ {user-mention}, please enable your dm and rejoin this server."
Verification: "> Please enter the code to get verified!"
Verified:
  title: "âœ… Verification"
  description: "> {user-username} has successfully verified their account!"
  color: "default"
  timestamp: true
Unverified:
  title: "âŒ Unverified"
  description: "> {user-username} you entered wrong captcha code!"
  color: "error"
  timestamp: true
Verification_Logs:
  title: "ğŸ” Verifiaction Result"
  description: "{user-mention} ({user-id}) has {status} verification process!"
  color: "default"
  timestamp: true


Logs:
  MessageDelete:
    title: "Message Deleted"
    description: "â†’ ***Author:*** {user-username} ({user-id})\nâ†’ ***Date:*** {date-time}\nâ†’ ***Channel:*** {channel-name} ({channel-id})\n\nâ†’ ***Content:*** {content}"
    color: 'default'
    footer: "Message Deleted - {guild-name}"
    timestamp: true
  MessageUpdate:
    title: "Message Edited"
    description: "â†’ ***Author:*** {user-username} ({user-id})\nâ†’ ***Date:*** {date-time}\nâ†’ ***Channel:*** {channel-name} ({channel-id})\n\nâ†’ ***Old Content:*** {old-content}\nâ†’ ***New Content:*** {new-content}"
    color: 'default'
    footer: "Message Edited - {guild-name}"
    timestamp: true
  AdvertisementDetected:
    title: "Advertisement Detected"
    description: "{user-mention} you have been warned for posting links in the server !"
    color: 'default'
    footer: "Advertisement - {guild-name}"
    timestamp: true
