Permission:
  title: "`âŒ` | No Perms"
  description: "> You don't have permission to run this command."
  color: "error"
  timestamp: true

Usage:
  title: "`âŒ` | Invalid Usage"
  description: "**Invalid Command Usage:**\n> `{usage}`"
  color: "error"
  timestamp: true

# Utils ....

Help:
  title: "`â“` | Help"
  color: "default"
  timestamp: true
  footer: "{guild-name}"
  footerIcon: "{guild-icon}"

Ping:
  title: "`â³` | Ping"
  color: "default"
  timestamp: true

Userinfo:
  title: "`ðŸ‘¤` | User Info"
  fields:
    - name: "â¯ Username"
      value: "{user_username}"
      inline: true
    - name: "â¯ ID"
      value: "{user_id}"
      inline: false
    - name: "â¯ Bot"
      value: "{bot}"
      inline: false
    - name: "â¯ Joined Discord"
      value: "{created_at}"
      inline: false
    - name: "â¯ Level"
      value: "{level}"
      inline: true
    - name: "â¯ Exp"
      value: "{exp}"
      inline: true
    - name: "â¯ Progress"
      value: "{progressExp}"
      inline: true
  thumbnail: "{user_avatar}"
  color: "success"
  timestamp: true

Serverinfo:
  title: "`ðŸŒ` | Server Info"
  fields:
    - name: "â¯ Server Name"
      value: "{guild-name}"
      inline: true
    - name: "â¯ ID"
      value: "{guild-id}"
      inline: true
    - name: "â¯ Members"
      value: "{guild-membercount}"
      inline: false
    - name: "â¯ Channels"
      value: "{guild-channelcount}"
      inline: true
    - name: "â¯ Roles"
      value: "{guild-rolecount}"
      inline: true
    - name: "â¯ Owner"
      value: "{guild-owner} `({guild-ownerid})`"
      inline: false
  thumbnail: "{guild-icon}"
  color: "default"
  timestamp: true

# Admin

FetchInvites:
  title: "`ðŸ”’` | Fetch Server Invites"
  description: "Server invites have been fetched successfully!"
  footer: "Total invites fetched: {size}"
  footerIcon: "{guild-icon}"
  color: "default"
  timestamp: true

Say:
  Embed:
    title: "`ðŸ“` | {guild-name}"
    description: "> {content}"
    color: "default"
    timestamp: true
  Sent:
    title: "{user-username}"
    description: "> Your message has been sent!"
    color: "default"
    timestamp: true

XpAdd:
  title: "Xp Add"
  description: "> {user-mention} has gained {xp} XP and reached new level: {level}"
  color: "default"
  timestamp: true

XpRemove:
  title: "Xp Remove"
  description: "> {user-mention} has lost {xp} XP and now is on level: {level}"
  color: "default"
  timestamp: true

Embed: 
  title: "Embed sent successfully!"
  description: "> Your embed `{embed-name}` has been sent in {channel-mention}"
  color: "default"
  timestamp: true

# Moderation

Clear:
  Success:
    title: "`âœ…` | Messages Cleared"
    description: "> {amount} messages cleared by {user-mention} in {channel-mention}"
    color: "success"
    timestamp: true
  Unable_to_clear:
    title: "`âŒ` | Unable to Clear"
    description: "> I couldn't delete the specified number of messages, messages older than 14 days cannot be deleted!"
    color: "error"

Ban:
  Success:
    title: "`ðŸ’¢` | Banned"
    description: "> {user-mention} has been successfully banned by {staff-mention}"
    color: "success"
    timestamp: true
  Higher_Staff:
    title: "Ban Error"
    description: "> You are not allowed to ban users with a role higher than yours."
    color: "error"
    timestamp: true
  Staff_Member:
    title: "Ban Error"
    description: "> You are not allowed to ban staff members."
    color: "error"
    timestamp: true

Kick:
  Success:
    title: "`ðŸ’¢` | Kicked"
    description: "> {user-mention} has been successfully kicked by {staff-mention}"
    color: "success"
    timestamp: true
  Higher_Staff:
    title: "Kick Error"
    description: "> You are not allowed to kick users with a role higher than yours."
    color: "error"
    timestamp: true
  Staff_Member:
    title: "Kick Error"
    description: "> You are not allowed to kick staff members."
    color: "error"
    timestamp: true

# Management

Prefix:
  title: "`ðŸŒ` | Prefix Set"
  description: "> The prefix for this server has been set to `{prefix}`."
  color: "default"
  footer: "{guild-name}"
  footerIcon: "{guild-icon}"
  timestamp: true

Setup:
  title: "Bot Setup"
  description: "> Bot setup has been completed successfully!"
  color: "default"
  timestamp: true
  footer: "{bot-username}"
  footerIcon: "{bot-pfp}"

# EXP

Leveltop:
  format: "**{position}: **{user-mention} â¯ `{level}` level â¯ `{exp}` exp"
  Embed:
    title: "â¯ Exp Top"
    description: "{formatedData}"
    color: "default"
    timestamp: true
    footer: "{guild-name}"
    footerIcon: "{guild-icon}"

Level:
  NoLevel:
    title: "{user-username} doesn't have any levels."
    color: "error"
  LevelMessage: "Level: {level}\nExp: {exp}\nYou need {neededExp} more exp to levelup!"

# Other

Boosters:
  Embed:
    title: "`ðŸ©·` | Boosters"
    description: "{boosters}"
    color: "default"
    timestamp: true
    footer: "{guild-name}"
  No_Boosters: "There is no active boosters in this server!"

Uptime:
  title: "Bot Uptime"
  description: "The bot has been online for **{uptime}**"
  timestamp: true
  color: "default"
  footer: "Erno"
  footerIcon: "{bot-pfp}"

# Leveling and Other

Levelup:
  title: "Level Up!"
  description: "> {user-mention} has reached level {level}!"
  color: "default"
  footer: "{guild-name}"
  footerIcon: "{guild-icon}"
  timestamp: true

Id:
  title: "`ðŸ”` | Id Lookup"
  color: "default"
  timestamp: true,
  footer: "{guild-name}"
  footerIcon: "{guild-icon}"

Avatar:
  title: "`ðŸ–¼ï¸` | Avatar"
  description: "> [Click here to view avatar]({user-pfp})"
  color: "default"
  image: "{user-pfp}"
  timestamp: true

Welcome: "Welcome to our server {user-username}, you are the #{memberCount} member!"
Leave: "Goodbye {user-username}, we hope to see you again soon!\nTotal members: {memberCount}"
